export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as Login} from './Login'
export {default as Posts} from './Posts'
export {default as Home} from './Home'
export {default as Register} from './Register.jsx'
export {default as SinglePost} from './SinglePost'
// export {default as SeeDetails} from './SeePostDetails'
